package com.rambo.cwe.jws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "UserService", targetNamespace = "http://inter.jws.cwe.rambo.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UserService {


    /**
     * @param name
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://inter.jws.cwe.rambo.com/UserService/sayHiRequest", output = "http://inter.jws.cwe.rambo.com/UserService/sayHiResponse")
    public String sayHi(@WebParam(name = "name", partName = "name") String name);

}
